### ISSUE TITLE
bs4 is not the beautifulsoup package

### ISSUE THREAD

**Issue by astrowonk** [vittoriotriassi/jobs_scraper#2]
You are requiring "bs4" but that's the wrong pypi package name. https://pypi.org/project/bs4/

You want to require beautifulsoup4

**Comment by vittoriotriassi** [comment]
Hi there! As you mentioned, that's a dummy package that would install beautifulsoup4 eventually.
As pointed out at your link: "This package ensures that if you type pip install bs4 by mistake you will end up with Beautiful Soup."

I noticed you forked the repo so you may have already replaced it with beautifulsoup4. 

Cheers :)
